const cards = [
    { word: "Beach", forbidden: ["Sand", "Ocean", "Sun", "Wave", "Vacation"] },
    { word: "Penguin", forbidden: ["Ice", "Snow", "Bird", "Cold", "Antarctica"] },
    { word: "Galaxy", forbidden: ["Stars", "Space", "Planets", "Universe", "Astronomy"] },
    { word: "Volcano", forbidden: ["Lava", "Eruption", "Ash", "Hot", "Smoke"] },
    { word: "Mountain", forbidden: ["Hiking", "Climbing", "Peak", "Rock", "Snow"] },
    { word: "Computer", forbidden: ["Keyboard", "Mouse", "Screen", "Internet", "Technology"] },
    { word: "Book", forbidden: ["Pages", "Read", "Library", "Story", "Author"] },
    { word: "Car", forbidden: ["Drive", "Road", "Engine", "Wheels", "Gas"] },
    { word: "Pizza", forbidden: ["Cheese", "Crust", "Pepperoni", "Slice", "Oven"] },
    { word: "Cat", forbidden: ["Feline", "Meow", "Whiskers", "Purr", "Kitten"] },
    { word: "Dog", forbidden: ["Bark", "Puppy", "Leash", "Fetch", "Tail"] },
    { word: "Tree", forbidden: ["Leaves", "Branches", "Forest", "Wood", "Roots"] },
    { word: "River", forbidden: ["Water", "Stream", "Flow", "Fishing", "Current"] },
    { word: "Airplane", forbidden: ["Flight", "Wings", "Pilot", "Travel", "Sky"] },
    { word: "Camera", forbidden: ["Photo", "Lens", "Picture", "Flash", "Zoom"] },
    { word: "Clock", forbidden: ["Time", "Hour", "Minute", "Tick", "Hands"] },
    { word: "Hospital", forbidden: ["Doctor", "Nurse", "Sick", "Patient", "Emergency"] },
    { word: "Movie", forbidden: ["Film", "Actor", "Cinema", "Theater", "Screen"] },
    { word: "Music", forbidden: ["Song", "Instrument", "Melody", "Notes", "Band"] },
    { word: "Bicycle", forbidden: ["Wheels", "Ride", "Pedal", "Helmet", "Chain"] },
    { word: "Rain", forbidden: ["Water", "Clouds", "Drops", "Storm", "Umbrella"] },
    { word: "Sun", forbidden: ["Light", "Heat", "Day", "Sky", "Shine"] },
    { word: "Moon", forbidden: ["Night", "Sky", "Orbit", "Space", "Tides"] },
    { word: "Rocket", forbidden: ["Space", "Launch", "NASA", "Astronaut", "Fuel"] },
    { word: "Soccer", forbidden: ["Goal", "Ball", "Field", "Team", "Kick"] },
    { word: "Basketball", forbidden: ["Hoop", "Dribble", "Court", "Team", "Shoot"] },
    { word: "Ice Cream", forbidden: ["Cold", "Dessert", "Cone", "Scoop", "Flavor"] },
    { word: "Chocolate", forbidden: ["Sweet", "Candy", "Brown", "Bar", "Cocoa"] },
    { word: "Train", forbidden: ["Tracks", "Engine", "Rail", "Station", "Travel"] },
    { word: "Bridge", forbidden: ["River", "Connect", "Arch", "Build", "Structure"] }
  ];
  
  